/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoaerolinea;

import Metodos.Metodos_sql;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ángel
 */
public class Consultar_Usuario extends javax.swing.JFrame {

    /**
     * Creates new form Consultar_Usuario
     */
    public Consultar_Usuario() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCURP = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_Consultas = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnBorrar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Adobe Heiti Std R", 1, 24)); // NOI18N
        jLabel1.setText("CONSULTAR USUARIO");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Ingrese su CURP:");

        Tabla_Consultas.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Tabla_Consultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellidos", "CURP", "Domicilio", "Celular", "Correo", "Contraseña", "Fecha_Nac", "Sexo"
            }
        ));
        Tabla_Consultas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabla_ConsultasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla_Consultas);

        btnBuscar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnRegresar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnRegresar.setText("REGRESAR");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/small.jpg"))); // NOI18N

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtCURP, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(btnBuscar)
                        .addGap(50, 50, 50)
                        .addComponent(btnBorrar)
                        .addGap(28, 28, 28)
                        .addComponent(btnActualizar)
                        .addGap(18, 18, 18)
                        .addComponent(btnRegresar)))
                .addContainerGap(183, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(287, 287, 287)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addComponent(jLabel3))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCURP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar)
                    .addComponent(btnRegresar)
                    .addComponent(btnBorrar)
                    .addComponent(btnActualizar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        Menu_Principal menu1=new Menu_Principal();
        menu1.setVisible(true);
        this.dispose();
        menu1.lblPrincipal.setVisible(false);
        
    }//GEN-LAST:event_btnRegresarActionPerformed
    
    private void actualizarUsuario(){
        
        int[] selected = Tabla_Consultas.getSelectedRows();
        int row = Tabla_Consultas.convertRowIndexToModel(Tabla_Consultas.getSelectedRow());
        int col_nombre = Tabla_Consultas.getColumnModel().getColumnIndex("Nombre");        
        int col_apellidos = Tabla_Consultas.getColumnModel().getColumnIndex("Apellidos");        
        int col_Curp = Tabla_Consultas.getColumnModel().getColumnIndex("CURP");        
        int col_domicilio = Tabla_Consultas.getColumnModel().getColumnIndex("Domicilio");        
        int col_celular= Tabla_Consultas.getColumnModel().getColumnIndex("Celular");        
        int col_correo = Tabla_Consultas.getColumnModel().getColumnIndex("Correo");        
        int col_contraseña = Tabla_Consultas.getColumnModel().getColumnIndex("Contraseña");        
        int col_nacimiento = Tabla_Consultas.getColumnModel().getColumnIndex("Fecha_Nac");        
        int col_sexo = Tabla_Consultas.getColumnModel().getColumnIndex("Sexo"); 
        
                
        String nombre = (String) Tabla_Consultas.getModel().getValueAt(row,col_nombre);        
        String apellidos = (String) Tabla_Consultas.getModel().getValueAt(row,col_apellidos);        
        String curp= (String) Tabla_Consultas.getModel().getValueAt(row,col_Curp);        
        String domicilio= (String) Tabla_Consultas.getModel().getValueAt(row,col_domicilio);        
        String celular= (String) Tabla_Consultas.getModel().getValueAt(row,col_celular);       
        String correo= (String) Tabla_Consultas.getModel().getValueAt(row,col_correo);        
        String contraseña= (String) Tabla_Consultas.getModel().getValueAt(row,col_contraseña);        
        String nacimiento= (String) Tabla_Consultas.getModel().getValueAt(row,col_nacimiento);        
        String sexo= (String) Tabla_Consultas.getModel().getValueAt(row,col_sexo);        
                        
        //System.out.println(Tabla_Consultas.getColumn("CURP"));
        System.out.println(row);
        //System.out.println(col_nombre);
        System.out.println(nombre);
        System.out.println(apellidos);
        System.out.println(curp);
        System.out.println(domicilio);
        System.out.println(celular);
        System.out.println(correo);
        System.out.println(contraseña);
        System.out.println(nacimiento);
        System.out.println(sexo);
    }
   
    
    private void borrarUsuario(){
        int[] selected = Tabla_Consultas.getSelectedRows();
        int row = Tabla_Consultas.convertRowIndexToModel(Tabla_Consultas.getSelectedRow());
        int col = Tabla_Consultas.getColumnModel().getColumnIndex("CURP");        
        String curp = (String) Tabla_Consultas.getModel().getValueAt(row,col);        
        //System.out.println(Tabla_Consultas.getColumn("CURP"));
        System.out.println(row);
        System.out.println(col);
        System.out.println(curp);
        /*
        try {
            Metodos.Metodos_sql eliminar = new Metodos_sql();
            int resultado = eliminar.eliminarUsuario(curp);
            JOptionPane.showMessageDialog(null, "Se elimino");
        } catch (SQLException ex) {
            Logger.getLogger(Consultar_Usuario.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "NO se elimino");
        }
        */
    }
    
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            
            DefaultTableModel tabla=(DefaultTableModel)Tabla_Consultas.getModel();
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/agencia_viajes","root","");
            Statement stmt=con.createStatement();
            //ResultSet rs=stmt.executeQuery("SELECT * FROM usuarios WHERE ID"+txtCURP.getText());
            ResultSet rs=stmt.executeQuery("SELECT * FROM usuarios WHERE CURP LIKE '"+txtCURP.getText()+"%' ORDER BY CURP DESC");
            
            rs.first();
            
            do {                
                String[] fila={rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9)};
                tabla.addRow(fila);
            } while (rs.next());
        } catch (SQLException ex) {
            Logger.getLogger(Consultar_Usuario.class.getName()).log(Level.SEVERE, null, ex);
             JOptionPane.showMessageDialog(this, "Ningun Usuario con ese CURP");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void Tabla_ConsultasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabla_ConsultasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Tabla_ConsultasMouseClicked

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        borrarUsuario();
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        actualizarUsuario();
    }//GEN-LAST:event_btnActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try{
//UIManager.setLookAndFeel("com.jtattoo.plaf.texture.TextureLookAndFeel");
//UIManager.setLookAndFeel("com.jtattoo.plaf.acryl.AcrylLookAndFeel");
//UIManager.setLookAndFeel("com.jtattoo.plaf.luna.LunaLookAndFeel");
//UIManager.setLookAndFeel("com.jtattoo.plaf.aero.AeroLookAndFeel");
//UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
//UIManager.setLookAndFeel("com.jtattoo.plaf.bernstein.BernsteinLookAndFeel");
//UIManager.setLookAndFeel("com.jtattoo.plaf.graphite.GraphiteLookAndFeel");
//UIManager.setLookAndFeel("com.jtattoo.plaf.hifi.HiFiLookAndFeel");
//UIManager.setLookAndFeel("com.jtattoo.plaf.fast.FastLookAndFeel");
UIManager.setLookAndFeel("com.jtattoo.plaf.mcwin.McWinLookAndFeel");
//UIManager.setLookAndFeel("com.jtattoo.plaf.mint.MintLookAndFeel");
}
catch (Exception e) {
JOptionPane.showMessageDialog(null, e);
}
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consultar_Usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla_Consultas;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCURP;
    // End of variables declaration//GEN-END:variables
}
