/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoaerolinea;

/**
 *
 * @author Ángel
 */
public class Informacion extends javax.swing.JFrame {

    /**
     * Creates new form Informacion
     */
    public Informacion() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnColiseo = new javax.swing.JButton();
        btnCristo = new javax.swing.JButton();
        btnMuralla = new javax.swing.JButton();
        btnMachu = new javax.swing.JButton();
        btnPetra = new javax.swing.JButton();
        btnChichen = new javax.swing.JButton();
        btnTaj = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnColiseo.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        btnColiseo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_Info1/Coliseo.jpg"))); // NOI18N
        btnColiseo.setText("Coliseo de Roma");
        btnColiseo.setContentAreaFilled(false);
        btnColiseo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnColiseo.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_Info1/Coliseo.jpg"))); // NOI18N
        btnColiseo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_Info/3/Coliseo.jpg"))); // NOI18N
        btnColiseo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnColiseo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColiseoActionPerformed(evt);
            }
        });

        btnCristo.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        btnCristo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_Info1/cristo.jpg"))); // NOI18N
        btnCristo.setText("Cristo Redentor");
        btnCristo.setContentAreaFilled(false);
        btnCristo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCristo.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_Info1/cristo.jpg"))); // NOI18N
        btnCristo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_Info/3/cristo.jpg"))); // NOI18N
        btnCristo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCristo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCristoActionPerformed(evt);
            }
        });

        btnMuralla.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        btnMuralla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_Info1/muralla.jpg"))); // NOI18N
        btnMuralla.setText("Muralla China");
        btnMuralla.setContentAreaFilled(false);
        btnMuralla.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMuralla.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_Info1/muralla.jpg"))); // NOI18N
        btnMuralla.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_Info/3/muralla.jpg"))); // NOI18N
        btnMuralla.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMuralla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMurallaActionPerformed(evt);
            }
        });

        btnMachu.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        btnMachu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_Info1/machu.jpg"))); // NOI18N
        btnMachu.setText("Machu Picchu");
        btnMachu.setContentAreaFilled(false);
        btnMachu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMachu.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_Info1/machu.jpg"))); // NOI18N
        btnMachu.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_Info/3/machu.jpg"))); // NOI18N
        btnMachu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMachu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMachuActionPerformed(evt);
            }
        });

        btnPetra.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        btnPetra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_Info1/petra.jpg"))); // NOI18N
        btnPetra.setText("Petra");
        btnPetra.setContentAreaFilled(false);
        btnPetra.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPetra.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_Info1/petra.jpg"))); // NOI18N
        btnPetra.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_Info/3/petra.jpg"))); // NOI18N
        btnPetra.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPetra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPetraActionPerformed(evt);
            }
        });

        btnChichen.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        btnChichen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_Info1/Chichen.jpg"))); // NOI18N
        btnChichen.setText("Chichén Itzá");
        btnChichen.setContentAreaFilled(false);
        btnChichen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnChichen.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_Info1/Chichen.jpg"))); // NOI18N
        btnChichen.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_Info/3/Chichen.jpg"))); // NOI18N
        btnChichen.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnChichen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChichenActionPerformed(evt);
            }
        });

        btnTaj.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        btnTaj.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_Info1/taj.jpg"))); // NOI18N
        btnTaj.setText("Tah Mahal");
        btnTaj.setContentAreaFilled(false);
        btnTaj.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTaj.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_Info1/taj.jpg"))); // NOI18N
        btnTaj.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_Info/3/taj.jpg"))); // NOI18N
        btnTaj.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTajActionPerformed(evt);
            }
        });

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/small.jpg"))); // NOI18N

        jButton2.setText("Comprar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnMuralla, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnChichen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(btnTaj, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnMachu, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnPetra, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnColiseo, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCristo, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(btnRegresar)
                        .addGap(112, 112, 112)
                        .addComponent(jButton2))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnCristo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnColiseo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnChichen, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPetra, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 4, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMachu, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMuralla, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(btnTaj, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnRegresar)
                                    .addComponent(jButton2))
                                .addGap(93, 93, 93))))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnColiseoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColiseoActionPerformed
        // TODO add your handling code here:
        Coliseo m1=new Coliseo();
         m1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnColiseoActionPerformed

    private void btnCristoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCristoActionPerformed
        // TODO add your handling code here:
        Cristo m1=new Cristo();
         m1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCristoActionPerformed

    private void btnMurallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMurallaActionPerformed
        // TODO add your handling code here:
        Muralla m1=new Muralla();
         m1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMurallaActionPerformed

    private void btnMachuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMachuActionPerformed
        // TODO add your handling code here:
        Machu m1=new Machu();
         m1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMachuActionPerformed

    private void btnPetraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPetraActionPerformed
        // TODO add your handling code here:
        Petra m1=new Petra();
         m1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPetraActionPerformed

    private void btnChichenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChichenActionPerformed
        // TODO add your handling code here:
        Chichen m1=new Chichen();
         m1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnChichenActionPerformed

    private void btnTajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTajActionPerformed
        // TODO add your handling code here:
        Taj m1=new Taj();
         m1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnTajActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        Menu_Principal menu1=new Menu_Principal();
        menu1.setVisible(true);
        this.dispose();
        menu1.lblPrincipal.setVisible(false);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Comprar compra=new Comprar();
        compra.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Informacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Informacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Informacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Informacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Informacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChichen;
    private javax.swing.JButton btnColiseo;
    private javax.swing.JButton btnCristo;
    private javax.swing.JButton btnMachu;
    private javax.swing.JButton btnMuralla;
    private javax.swing.JButton btnPetra;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnTaj;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
